# Generated by Django 5.0.6 on 2026-06-14 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('daily_revenue', 'Daily Revenue Report'), ('occupancy', 'Occupancy Report'), ('guest_ledger', 'Guest Ledger'), ('staff_attendance', 'Staff Attendance Summary'), ('inventory_consumption', 'Inventory Consumption'), ('profit_loss', 'P&L Summary'), ('nepal_vat', 'Nepal VAT Report'), ('payroll', 'Payroll Summary')], max_length=50)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('task_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Report Export',
                'verbose_name_plural': 'Report Exports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('room_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('restaurant_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('other_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('occupied_rooms', models.IntegerField(default=0)),
                ('total_rooms', models.IntegerField(default=0)),
                ('occupancy_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('adr', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('revpar', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_guests', models.IntegerField(default=0)),
                ('new_guests', models.IntegerField(default=0)),
                ('restaurant_covers', models.IntegerField(default=0)),
                ('avg_restaurant_spend', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to='properties.property')),
            ],
            options={
                'verbose_name': 'Daily Metric',
                'verbose_name_plural': 'Daily Metrics',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date', 'property'], name='analytics_d_date_6cd14a_idx')],
                'unique_together': {('property', 'date')},
            },
        ),
    ]
