# Generated by Django 5.0.6 on 2026-06-14 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_checkin_time', models.DateTimeField(auto_now_add=True)),
                ('id_document_image', models.CharField(blank=True, help_text='Path to uploaded guest ID document in MinIO', max_length=255)),
                ('key_issued', models.CharField(blank=True, help_text='Physical room key/card identifier issued to guest', max_length=50)),
                ('locker_number', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_in_guests', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='check_in_record', to='bookings.reservation')),
            ],
            options={
                'verbose_name': 'Check In',
                'verbose_name_plural': 'Check Ins',
            },
        ),
        migrations.CreateModel(
            name='CheckOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_checkout_time', models.DateTimeField(auto_now_add=True)),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('additional_charges', models.JSONField(blank=True, default=list, help_text='Custom list of [{description, amount}] charges appended at checkout')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Credit/Debit Card'), ('esewa', 'eSewa'), ('khalti', 'Khalti'), ('fonepay', 'Fonepay'), ('bank_transfer', 'Bank Transfer')], default='cash', max_length=30)),
                ('feedback_rating', models.PositiveIntegerField(blank=True, null=True)),
                ('feedback_comment', models.TextField(blank=True)),
                ('checked_out_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_out_guests', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='check_out_record', to='bookings.reservation')),
            ],
            options={
                'verbose_name': 'Check Out',
                'verbose_name_plural': 'Check Outs',
            },
        ),
    ]
