# Generated by Django 5.0.6 on 2026-06-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontdesk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Credit/Debit Card'), ('esewa', 'eSewa'), ('khalti', 'Khalti'), ('fonepay', 'Fonepay'), ('bank_transfer', 'Bank Transfer'), ('split', 'Split')], default='cash', max_length=30),
        ),
    ]
