# Generated by Django 5.0.6 on 2026-06-14 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=30)),
                ('nationality', models.CharField(default='Nepalese', max_length=100)),
                ('id_type', models.CharField(choices=[('passport', 'Passport'), ('citizenship', 'Citizenship Card'), ('driving_license', 'Driving License'), ('other', 'Other')], default='citizenship', max_length=30)),
                ('id_number', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True, help_text='General notes about guest behavior or requests')),
                ('dietary_restrictions', models.TextField(blank=True)),
                ('preferences', models.TextField(blank=True)),
                ('is_blacklisted', models.BooleanField(default=False)),
                ('blacklist_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Guest Profile',
                'verbose_name_plural': 'Guest Profiles',
                'indexes': [models.Index(fields=['phone'], name='bookings_gu_phone_3a36e8_idx'), models.Index(fields=['email'], name='bookings_gu_email_4abf12_idx')],
            },
        ),
        migrations.CreateModel(
            name='RatePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('min_nights', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_plans', to='properties.roomtype')),
            ],
            options={
                'verbose_name': 'Rate Plan',
                'verbose_name_plural': 'Rate Plans',
                'ordering': ['valid_from'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('adults', models.PositiveIntegerField(default=1)),
                ('children', models.PositiveIntegerField(default=0)),
                ('infants', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='pending', max_length=25)),
                ('booking_source', models.CharField(choices=[('direct', 'Direct Staff Booking'), ('phone', 'Phone Reservation'), ('walk_in', 'Walk-in Guest'), ('online', 'Online Website Direct'), ('ota_booking', 'OTA Booking.com'), ('ota_agoda', 'OTA Agoda'), ('ota_expedia', 'OTA Expedia')], default='direct', max_length=30)),
                ('total_nights', models.PositiveIntegerField()),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deposit_paid', models.BooleanField(default=False)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('special_requests', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reservations', to=settings.AUTH_USER_MODEL)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='bookings.guestprofile')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='properties.room')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
                'indexes': [models.Index(fields=['check_in_date', 'check_out_date'], name='bookings_re_check_i_6353ea_idx'), models.Index(fields=['status'], name='bookings_re_status_5afb4b_idx')],
            },
        ),
    ]
