"""
SIA HMS — Fonepay Merchant QR Integration
Reference Specifications for Fonepay QR payment and status checks.

TODO / STUB WARNING:
--------------------
This module is currently running in SANDBOX/MOCK mode because production Fonepay
merchant credentials are not yet configured.

To complete production configuration:
1. Obtain MD (Merchant ID), MC (Merchant Code), and Secret Key from Fonepay.
2. Set them in config/settings/production.py and the environment:
   - FONEPAY_MERCHANT_CODE
   - FONEPAY_SECRET_KEY
   - FONEPAY_SANDBOX = False
3. Fonepay's real API endpoints require a secure production connection.
"""

import hmac
import hashlib
import urllib.parse
import requests
import logging
from django.conf import settings
from django.utils import timezone

logger = logging.getLogger(__name__)

# Fonepay API Endpoints (Sandbox/UAT vs Production)
FONEPAY_UAT_URL = "https://dev-api.fonepay.com/api/merchantRequest"
FONEPAY_PROD_URL = "https://api.fonepay.com/api/merchantRequest"


def get_fonepay_endpoint(action: str) -> str:
    """
    Returns the appropriate Fonepay URL based on the sandbox settings.
    """
    base_url = FONEPAY_UAT_URL if getattr(settings, "FONEPAY_SANDBOX", True) else FONEPAY_PROD_URL
    # Actions: 'qrGenerate' or 'paymentVerification'
    return f"{base_url}/{action}"


def generate_fonepay_signature(data: dict) -> str:
    """
    Generates Fonepay data verification (DV) signature using HMAC-SHA256.
    The string is generated by concatenating values in the order defined by Fonepay:
    Format: PRN,AMT,CRN,DT,R1,R2,MD,MC,RU
    """
    secret_key = getattr(settings, "FONEPAY_SECRET_KEY", "")
    if not secret_key:
        logger.warning("FONEPAY_SECRET_KEY is empty. Signature will be invalid.")
        return ""

    # Sort/Concatenate values in the exact protocol order
    # protocol parameters: PRN (Product Ref), AMT (Amount), CRN (Currency), DT (Date), R1, R2, MD, MC, RU (Return URL)
    ordered_keys = ["PRN", "AMT", "CRN", "DT", "R1", "R2", "MD", "MC", "RU"]
    message_parts = []
    for k in ordered_keys:
        message_parts.append(str(data.get(k, "")))

    message = ",".join(message_parts)
    
    # HMAC-SHA256
    key_bytes = secret_key.encode("utf-8")
    message_bytes = message.encode("utf-8")
    
    signature = hmac.new(key_bytes, message_bytes, hashlib.sha256).hexdigest()
    return signature


def initiate_fonepay_qr(amount_npr: float, transaction_id: str, return_url: str) -> dict:
    """
    Initiates payment and requests Fonepay to generate a dynamic merchant QR.
    Returns the QR URL or QR data payload.
    """
    sandbox = getattr(settings, "FONEPAY_SANDBOX", True)
    merchant_code = getattr(settings, "FONEPAY_MERCHANT_CODE", "")
    secret_key = getattr(settings, "FONEPAY_SECRET_KEY", "")

    # Fallback to Sandbox mock if credentials are not set
    if sandbox or not merchant_code or not secret_key:
        logger.info(f"Fonepay running in sandbox/mock. Mocking QR generation for TX-{transaction_id}")
        return {
            "status": "success",
            "qr_code_url": f"https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=FONEPAY_MOCK_TX_{transaction_id}",
            "prn": f"TX-{transaction_id}",
            "message": "MOCK_QR_GENERATED"
        }

    url = get_fonepay_endpoint("qrGenerate")
    
    payload = {
        "PRN": f"TX-{transaction_id}",
        "AMT": f"{amount_npr:.2f}",
        "CRN": "NPR",
        "DT": timezone.now().strftime("%m/%d/%Y"),
        "R1": f"HMS-Bill-{transaction_id}",
        "R2": "Hotel Room Payment",
        "MD": merchant_code,  # Merchant ID
        "MC": merchant_code,  # Merchant Code
        "RU": return_url,     # Return URL
    }
    
    # Compute signature
    payload["DV"] = generate_fonepay_signature(payload)
    
    try:
        response = requests.post(url, json=payload, timeout=10)
        if response.status_code == 200:
            res_data = response.json()
            # Fonepay structure returns status code and QR code text
            if res_data.get("responseCode") == "0" or res_data.get("status") == "success":
                return {
                    "status": "success",
                    "qr_code_url": res_data.get("qrCode") or res_data.get("qrUrl"),
                    "prn": payload["PRN"],
                }
            else:
                logger.error(f"Fonepay API error: {res_data}")
                return {"status": "failed", "error": res_data.get("message", "Unknown Fonepay Error")}
        else:
            logger.error(f"Fonepay http failure: {response.status_code} - {response.text}")
            return {"status": "failed", "error": f"HTTP {response.status_code}"}
    except Exception as e:
        logger.exception("Fonepay QR generation request failed.")
        return {"status": "failed", "error": str(e)}


def verify_fonepay_status(transaction_id: str, amount_npr: float) -> dict:
    """
    Checks payment status with Fonepay's verification API.
    """
    sandbox = getattr(settings, "FONEPAY_SANDBOX", True)
    merchant_code = getattr(settings, "FONEPAY_MERCHANT_CODE", "")
    secret_key = getattr(settings, "FONEPAY_SECRET_KEY", "")

    # Fallback to Sandbox mock if credentials are not set
    if sandbox or not merchant_code or not secret_key:
        logger.info(f"Fonepay verification in sandbox/mock for TX-{transaction_id}")
        return {
            "status": "success",
            "response_code": "0",
            "message": "Payment completed successfully (Mock)",
            "transaction_code": f"FP-MOCK-{transaction_id}"
        }

    url = get_fonepay_endpoint("paymentVerification")
    
    # Verification requires PRN, MD, MC, AMT and DV signature
    payload = {
        "PRN": f"TX-{transaction_id}",
        "MD": merchant_code,
        "MC": merchant_code,
        "AMT": f"{amount_npr:.2f}",
    }
    
    # Fonepay verification signature is computed by concatenating: PRN,MD,MC,AMT
    message = f"{payload['PRN']},{payload['MD']},{payload['MC']},{payload['AMT']}"
    key_bytes = secret_key.encode("utf-8")
    message_bytes = message.encode("utf-8")
    payload["DV"] = hmac.new(key_bytes, message_bytes, hashlib.sha256).hexdigest()

    try:
        response = requests.post(url, json=payload, timeout=10)
        if response.status_code == 200:
            res_data = response.json()
            # responseCode "0" typically indicates success in Fonepay
            if res_data.get("responseCode") == "0":
                return {
                    "status": "success",
                    "response_code": "0",
                    "message": res_data.get("message", "Success"),
                    "transaction_code": res_data.get("uniqueId") or res_data.get("traceId"),
                }
            else:
                return {
                    "status": "pending",
                    "response_code": res_data.get("responseCode"),
                    "message": res_data.get("message", "Pending or Failed"),
                }
        else:
            return {"status": "error", "message": f"HTTP {response.status_code}"}
    except Exception as e:
        logger.exception("Fonepay verification query failed.")
        return {"status": "error", "message": str(e)}


def verify_fonepay_webhook_signature(payload: dict, signature: str) -> bool:
    """
    Verifies signature of incoming Fonepay notification callback webhooks.
    """
    secret_key = getattr(settings, "FONEPAY_SECRET_KEY", "")
    if not secret_key:
        return False
        
    # Signature input: Concatenated properties in Fonepay callback
    # e.g., PRN,PID,UID,AMT,STATUS
    prn = payload.get("PRN", "")
    pid = payload.get("PID", "")
    uid = payload.get("UID", "")
    amt = payload.get("AMT", "")
    status = payload.get("STATUS", "")
    
    message = f"{prn},{pid},{uid},{amt},{status}"
    key_bytes = secret_key.encode("utf-8")
    message_bytes = message.encode("utf-8")
    
    expected_sig = hmac.new(key_bytes, message_bytes, hashlib.sha256).hexdigest()
    return hmac.compare_digest(expected_sig, signature)
