# Generated by Django 5.0.6 on 2026-06-14 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(help_text='Month of the cycle (1-12)')),
                ('year', models.IntegerField(help_text='Year of the cycle (e.g., 2026)')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('processing', 'Processing'), ('approved', 'Approved'), ('paid', 'Paid')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payroll Period',
                'verbose_name_plural': 'Payroll Periods',
                'ordering': ['-year', '-month'],
                'unique_together': {('month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='PayrollEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_days', models.DecimalField(decimal_places=1, default=0.0, max_digits=4)),
                ('present_days', models.DecimalField(decimal_places=1, default=0.0, max_digits=4)),
                ('absent_days', models.DecimalField(decimal_places=1, default=0.0, max_digits=4)),
                ('leave_days', models.DecimalField(decimal_places=1, default=0.0, max_digits=4)),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('overtime_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('overtime_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('allowances', models.JSONField(blank=True, default=list)),
                ('deductions', models.JSONField(blank=True, default=list)),
                ('ssf_employee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ssf_employer', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('income_tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('gross_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('net_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_approved', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payroll_entries', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_entries', to='staff.staffmember')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='payroll.payrollperiod')),
            ],
            options={
                'verbose_name': 'Payroll Entry',
                'verbose_name_plural': 'Payroll Entries',
                'ordering': ['staff'],
                'unique_together': {('period', 'staff')},
            },
        ),
    ]
