# Generated by Django 5.0.6 on 2026-06-15 08:02

from django.db import migrations, models

def seed_tax_slabs_and_ssf(apps, schema_editor):
    TaxSlab = apps.get_model('payroll', 'TaxSlab')
    SSFConfig = apps.get_model('payroll', 'SSFConfig')

    # Seed SSF Config for 2081/82
    SSFConfig.objects.get_or_create(
        fiscal_year="2081/82",
        defaults={
            "employee_rate_percent": 11.00,
            "employer_rate_percent": 20.00,
            "is_active": True
        }
    )

    # Slabs for 2081/82
    slabs_data = [
        # Single
        {"fiscal_year": "2081/82", "filing_status": "single", "slab_order": 1, "min_amount": 0, "max_amount": 500000, "rate_percent": 1},
        {"fiscal_year": "2081/82", "filing_status": "single", "slab_order": 2, "min_amount": 500000, "max_amount": 700000, "rate_percent": 10},
        {"fiscal_year": "2081/82", "filing_status": "single", "slab_order": 3, "min_amount": 700000, "max_amount": 1000000, "rate_percent": 20},
        {"fiscal_year": "2081/82", "filing_status": "single", "slab_order": 4, "min_amount": 1000000, "max_amount": 2000000, "rate_percent": 30},
        {"fiscal_year": "2081/82", "filing_status": "single", "slab_order": 5, "min_amount": 2000000, "max_amount": 5000000, "rate_percent": 36},
        {"fiscal_year": "2081/82", "filing_status": "single", "slab_order": 6, "min_amount": 5000000, "max_amount": None, "rate_percent": 39},
        
        # Married
        {"fiscal_year": "2081/82", "filing_status": "married", "slab_order": 1, "min_amount": 0, "max_amount": 600000, "rate_percent": 1},
        {"fiscal_year": "2081/82", "filing_status": "married", "slab_order": 2, "min_amount": 600000, "max_amount": 800000, "rate_percent": 10},
        {"fiscal_year": "2081/82", "filing_status": "married", "slab_order": 3, "min_amount": 800000, "max_amount": 1100000, "rate_percent": 20},
        {"fiscal_year": "2081/82", "filing_status": "married", "slab_order": 4, "min_amount": 1100000, "max_amount": 2000000, "rate_percent": 30},
        {"fiscal_year": "2081/82", "filing_status": "married", "slab_order": 5, "min_amount": 2000000, "max_amount": 5000000, "rate_percent": 36},
        {"fiscal_year": "2081/82", "filing_status": "married", "slab_order": 6, "min_amount": 5000000, "max_amount": None, "rate_percent": 39},
    ]

    for item in slabs_data:
        TaxSlab.objects.get_or_create(
            fiscal_year=item["fiscal_year"],
            filing_status=item["filing_status"],
            slab_order=item["slab_order"],
            defaults={
                "min_amount": item["min_amount"],
                "max_amount": item["max_amount"],
                "rate_percent": item["rate_percent"]
            }
        )

def reverse_seed(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSFConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.CharField(help_text='e.g., 2081/82', max_length=10, unique=True)),
                ('employee_rate_percent', models.DecimalField(decimal_places=2, default=11.0, max_digits=5)),
                ('employer_rate_percent', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'SSF Configuration',
                'verbose_name_plural': 'SSF Configurations',
                'ordering': ['-fiscal_year'],
            },
        ),
        migrations.CreateModel(
            name='TaxSlab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.CharField(help_text='e.g., 2081/82', max_length=10)),
                ('filing_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married')], default='single', max_length=15)),
                ('slab_order', models.IntegerField(help_text='Order of the tax slab (1, 2, 3...)')),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rate_percent', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name': 'Tax Slab',
                'verbose_name_plural': 'Tax Slabs',
                'ordering': ['fiscal_year', 'filing_status', 'slab_order'],
                'unique_together': {('fiscal_year', 'filing_status', 'slab_order')},
            },
        ),
        migrations.RunPython(seed_tax_slabs_and_ssf, reverse_code=reverse_seed),
    ]
