# Generated by Django 5.0.6 on 2026-06-14 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(help_text='Lucide-react icon identifier (e.g., wifi, tv)', max_length=100)),
                ('category', models.CharField(choices=[('room', 'Room'), ('bathroom', 'Bathroom'), ('hotel', 'Hotel/General'), ('media', 'Media & Tech'), ('food', 'Food & Drink')], default='room', max_length=50)),
            ],
            options={
                'verbose_name': 'Amenity',
                'verbose_name_plural': 'Amenities',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tagline', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(default='Nepal', max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, help_text='Logo image stored in MinIO', null=True, upload_to='properties/')),
                ('cover_image', models.ImageField(blank=True, help_text='Cover image stored in MinIO', null=True, upload_to='properties/')),
                ('currency', models.CharField(default='NPR', max_length=10)),
                ('timezone', models.CharField(default='Asia/Kathmandu', max_length=100)),
                ('vat_number', models.CharField(blank=True, max_length=50)),
                ('pan_number', models.CharField(blank=True, max_length=50)),
                ('check_in_time', models.TimeField(default='14:00:00')),
                ('check_out_time', models.TimeField(default='12:00:00')),
                ('cancellation_policy', models.TextField(blank=True)),
                ('terms', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('max_occupancy', models.PositiveIntegerField(default=2)),
                ('base_price_per_night', models.DecimalField(decimal_places=2, help_text='Standard weekday rate', max_digits=12)),
                ('weekend_price', models.DecimalField(blank=True, decimal_places=2, help_text='Rate applicable on weekends (optional)', max_digits=12, null=True)),
                ('extra_person_charge', models.DecimalField(decimal_places=2, default=0.0, help_text='Charge per extra guest above double occupancy', max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amenities', models.ManyToManyField(blank=True, related_name='room_types', to='properties.amenity')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to='properties.property')),
            ],
            options={
                'verbose_name': 'Room Type',
                'verbose_name_plural': 'Room Types',
                'ordering': ['display_order', 'name'],
                'unique_together': {('property', 'name')},
            },
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rooms/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('is_primary', models.BooleanField(default=False, help_text='If True, this image is used as the cover photo for this room type')),
                ('display_order', models.IntegerField(default=0)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.roomtype')),
            ],
            options={
                'verbose_name': 'Room Image',
                'verbose_name_plural': 'Room Images',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=50, unique=True)),
                ('floor', models.IntegerField(help_text='Floor level (e.g. 0 for Ground, 1 for First Floor)')),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('dirty', 'Dirty'), ('maintenance', 'Maintenance'), ('out_of_order', 'Out of Order')], default='available', max_length=25)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('last_cleaned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='properties.roomtype')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'ordering': ['floor', 'room_number'],
            },
        ),
    ]
