# Generated by Django 5.0.6 on 2026-06-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='advance_deposit_percent',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='property',
            name='cancellation_refund_percent',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='property',
            name='free_cancellation_days',
            field=models.IntegerField(default=2),
        ),
    ]
