# Generated by Django 5.0.6 on 2026-06-15 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('ne', 'Nepali')], default='en', max_length=5),
        ),
    ]
