# Generated by Django 5.0.6 on 2026-06-15 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_preferred_language'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpersonationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impersonations_started', to=settings.AUTH_USER_MODEL)),
                ('target_tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impersonations', to='tenants.client')),
            ],
            options={
                'verbose_name': 'Impersonation Log',
                'verbose_name_plural': 'Impersonation Logs',
                'ordering': ['-started_at'],
            },
        ),
    ]
