# Generated by Django 5.0.6 on 2026-06-14 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('campaign_type', models.CharField(choices=[('birthday', 'Birthday Campaign'), ('anniversary', 'Anniversary Campaign'), ('winback', 'Winback Offer'), ('promotion', 'Generic Promotional Offer')], default='promotion', max_length=30)),
                ('message_template', models.TextField(help_text='SMS content template')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('queued', 'Queued'), ('sent', 'Sent')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuestActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('booking_create', 'Booking Created'), ('check_in', 'Checked In'), ('check_out', 'Checked Out'), ('payment', 'Payment Logged'), ('loyalty_earn', 'Points Earned'), ('loyalty_redeem', 'Points Redeemed'), ('profile_update', 'Profile Updated')], max_length=30)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='bookings.guestprofile')),
            ],
            options={
                'verbose_name': 'Guest Activity',
                'verbose_name_plural': 'Guest Activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuestTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='#cbd5e0', help_text='Hex code color representation', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guests', models.ManyToManyField(blank=True, related_name='tags', to='bookings.guestprofile')),
            ],
            options={
                'verbose_name': 'Guest Tag',
                'verbose_name_plural': 'Guest Tags',
                'ordering': ['name'],
            },
        ),
    ]
