# Generated by Django 5.0.6 on 2026-06-14 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Hotel / property name', max_length=100)),
                ('schema_name', models.CharField(max_length=63, unique=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('subscription_plan', models.CharField(blank=True, choices=[('starter', 'Starter (NPR 3,000/mo)'), ('professional', 'Professional (NPR 6,000/mo)'), ('enterprise', 'Enterprise (NPR 12,000/mo)'), ('private_install', 'Private Installation (One-time)')], default='starter', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('onboarded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Client / Tenant',
                'verbose_name_plural': 'Clients / Tenants',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.client')),
            ],
            options={
                'verbose_name': 'Domain',
                'verbose_name_plural': 'Domains',
            },
        ),
    ]
